Traceback (most recent call last):
  File "/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
recs = tcp.Records(data = 'puf.csv')
pol = tcp.Policy()
calc1 = tcp.Calculator(policy = pol, records = recs)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
File [0;32m/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/taxcalc/utils.py:1487[0m, in [0;36mread_egg_csv[0;34m(fname, index_col)[0m
[1;32m   1485[0m     path_in_egg [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin([38;5;124m'[39m[38;5;124mtaxcalc[39m[38;5;124m'[39m, fname)
[1;32m   1486[0m     vdf [38;5;241m=[39m pd[38;5;241m.[39mread_csv(
[0;32m-> 1487[0m         [43mpkg_resources[49m[38;5;241;43m.[39;49m[43mresource_stream[49m[43m([49m
[1;32m   1488[0m [43m            [49m[43mpkg_resources[49m[38;5;241;43m.[39;49m[43mRequirement[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mtaxcalc[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m,[49m
[1;32m   1489[0m [43m            [49m[43mpath_in_egg[49m[43m)[49m,
[1;32m   1490[0m         index_col[38;5;241m=[39mindex_col
[1;32m   1491[0m     )
[1;32m   1492[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:

File [0;32m/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/pkg_resources/__init__.py:1187[0m, in [0;36mResourceManager.resource_stream[0;34m(self, package_or_requirement, resource_name)[0m
[1;32m   1186[0m [38;5;250m[39m[38;5;124;03m"""Return a readable file-like object for specified resource"""[39;00m
[0;32m-> 1187[0m [38;5;28;01mreturn[39;00m [43mget_provider[49m[43m([49m[43mpackage_or_requirement[49m[43m)[49m[38;5;241;43m.[39;49m[43mget_resource_stream[49m[43m([49m
[1;32m   1188[0m [43m    [49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mresource_name[49m
[1;32m   1189[0m [43m[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/pkg_resources/__init__.py:1693[0m, in [0;36mDefaultProvider.get_resource_stream[0;34m(self, manager, resource_name)[0m
[1;32m   1692[0m [38;5;28;01mdef[39;00m [38;5;21mget_resource_stream[39m([38;5;28mself[39m, manager, resource_name):
[0;32m-> 1693[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mopen[39;49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_fn[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mmodule_path[49m[43m,[49m[43m [49m[43mresource_name[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/taxcalc/puf.csv'

During handling of the above exception, another exception occurred:

[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m recs [38;5;241m=[39m [43mtcp[49m[38;5;241;43m.[39;49m[43mRecords[49m[43m([49m[43mdata[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mpuf.csv[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m pol [38;5;241m=[39m tcp[38;5;241m.[39mPolicy()
[1;32m      3[0m calc1 [38;5;241m=[39m tcp[38;5;241m.[39mCalculator(policy [38;5;241m=[39m pol, records [38;5;241m=[39m recs)

File [0;32m/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/taxcalc/records.py:129[0m, in [0;36mRecords.__init__[0;34m(self, data, start_year, gfactors, weights, adjust_ratios, exact_calculations)[0m
[1;32m    127[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(weights, [38;5;28mstr[39m):
[1;32m    128[0m     weights [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(Records[38;5;241m.[39mCODE_PATH, weights)
[0;32m--> 129[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43mstart_year[49m[43m,[49m[43m [49m[43mgfactors[49m[43m,[49m[43m [49m[43mweights[49m[43m)[49m
[1;32m    130[0m [38;5;28;01mif[39;00m data [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    131[0m     [38;5;28;01mreturn[39;00m  [38;5;66;03m# because there are no data[39;00m

File [0;32m/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/taxcalc/data.py:92[0m, in [0;36mData.__init__[0;34m(self, data, start_year, gfactors, weights)[0m
[1;32m     90[0m [38;5;28mself[39m[38;5;241m.[39m__current_year [38;5;241m=[39m start_year
[1;32m     91[0m [38;5;66;03m# read specified data[39;00m
[0;32m---> 92[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_read_data[49m[43m([49m[43mdata[49m[43m)[49m
[1;32m     93[0m [38;5;66;03m# handle growth factors[39;00m
[1;32m     94[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m__aging_data:

File [0;32m/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/taxcalc/data.py:203[0m, in [0;36mData._read_data[0;34m(self, data)[0m
[1;32m    201[0m         taxdf [38;5;241m=[39m pd[38;5;241m.[39mread_csv(data)
[1;32m    202[0m     [38;5;28;01melse[39;00m:  [38;5;66;03m# find file in conda package[39;00m
[0;32m--> 203[0m         taxdf [38;5;241m=[39m [43mread_egg_csv[49m[43m([49m[43mdata[49m[43m)[49m  [38;5;66;03m# pragma: no cover[39;00m
[1;32m    204[0m [38;5;28;01melse[39;00m:
[1;32m    205[0m     msg [38;5;241m=[39m [38;5;124m'[39m[38;5;124mdata is neither a string nor a Pandas DataFrame[39m[38;5;124m'[39m

File [0;32m/usr/share/miniconda/envs/taxcalcpayroll-dev/lib/python3.8/site-packages/taxcalc/utils.py:1493[0m, in [0;36mread_egg_csv[0;34m(fname, index_col)[0m
[1;32m   1486[0m     vdf [38;5;241m=[39m pd[38;5;241m.[39mread_csv(
[1;32m   1487[0m         pkg_resources[38;5;241m.[39mresource_stream(
[1;32m   1488[0m             pkg_resources[38;5;241m.[39mRequirement[38;5;241m.[39mparse([38;5;124m'[39m[38;5;124mtaxcalc[39m[38;5;124m'[39m),
[1;32m   1489[0m             path_in_egg),
[1;32m   1490[0m         index_col[38;5;241m=[39mindex_col
[1;32m   1491[0m     )
[1;32m   1492[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[0;32m-> 1493[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124mcould not read [39m[38;5;132;01m{}[39;00m[38;5;124m data from egg[39m[38;5;124m'[39m[38;5;241m.[39mformat(fname))
[1;32m   1494[0m [38;5;66;03m# cannot call read_egg_ function in unit tests[39;00m
[1;32m   1495[0m [38;5;28;01mreturn[39;00m vdf

[0;31mValueError[0m: could not read puf.csv data from egg

